export const APP_ROUTES = {
  home: "/",
  login: "/login",
  developer: {
    root: "/developer",
    dashboard: "/developer/dashboard",
    schools: "/developer/schools",
    userAccounts: "/developer/user-accounts",
    schoolFeatures: "/developer/school-features",
    accessControl: "/developer/access-control",
    messageConfig: "/developer/message-config",
    webAppSettings: "/developer/web-app-settings",
    branding: "/developer/branding",
    auditLogs: "/developer/audit-logs",
  },
  school: {
    root: "/school",
    admin: {
      root: "/school/admin",
      dashboard: "/school/admin/dashboard",
      school: "/school/admin/school",
      students: "/school/admin/students",
      staff: "/school/admin/staff",
      fees: "/school/admin/fees",
      classes: "/school/admin/classes",
      syllabus: "/school/admin/syllabus",
      exams: "/school/admin/exams",
      results: "/school/admin/results",
      profile: "/school/admin/profile",
      settings: "/school/admin/settings",
    },
    teacher: {
      root: "/school/teacher",
      dashboard: "/school/teacher/dashboard",
      school: "/school/teacher/school",
      staff: "/school/teacher/staff",
      students: "/school/teacher/students",
      classes: "/school/teacher/classes",
      syllabus: "/school/teacher/syllabus",
      exams: "/school/teacher/exams",
      results: "/school/teacher/results",
      profile: "/school/teacher/profile",
      settings: "/school/teacher/settings",
    },
    staff: {
      root: "/school/staff",
      dashboard: "/school/staff/dashboard",
      school: "/school/staff/school",
      staff: "/school/staff/staff",
      students: "/school/staff/students",
      fees: "/school/staff/fees",
      classes: "/school/staff/classes",
      results: "/school/staff/results",
      profile: "/school/staff/profile",
      settings: "/school/staff/settings",
    },
    student: {
      root: "/school/student",
      dashboard: "/school/student/dashboard",
      results: "/school/student/results",
    },
  },
} as const;
